language: java
jdk:
  - openjdk8

before_deploy:
  - mvn deploy

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
  on:
    repo: SimonIT/idea-batch
    tags: true
    all_branches: true
