language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DfinalName=ClickWarp-$TRAVIS_TAG

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: target/ClickWarp-$TRAVIS_TAG.jar
  on:
    repo: SimonIT/ClickWarp
    tags: true
    all_branches: true
