language: java
jdk:
  - openjdk8

before_deploy:
  - mvn package

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: target/ClickWarp-*.jar
  on:
    repo: SimonIT/ClickWarp
    tags: true
    all_branches: true
