#   ____ _ _      _   __        __
#  / ___| (_) ___| | _\ \      / /_ _ _ __ _ __
# | |   | | |/ __| |/ /\ \ /\ / / _` | '__| '_ \
# | |___| | | (__|   <  \ V  V / (_| | |  | |_) |
#  \____|_|_|\___|_|\_\  \_/\_/ \__,_|_|  | .__/
#                                         |_|
# Plugin by comniemeer
# The configurable command method is from PostCrafter (excellent german video tutorials on YouTube: http://www.youtube.com/user/PostCrafter)
# Version 1.4.0
# Main configuration File

# Possible languages: en (English), de (Deutsch), fr (French), pt (Portuguese), cz (Czech) or ko (Korean)
# Or add your own language file to the "Languages" folder and type here the name of the file.
Language: en

Commands:
  warp: warp
  invwarp: invwarp
  editwarp: editwarp
  setwarp: setwarp
  delwarp: delwarp
  invtp: invtp
  invtpa: invtpa
  gettpskull: gettpskull

# Define here the default item for /invwarp
# Attention! If you use an item with an additional meta, like blue wool (wool:11),
# you have to make that item in '' (example: DefaultWarpItem: 'wool:11')!
DefaultWarpItem: grass

# If you wish to use an item that opens the "/invwarp" menu, enable it here and define an item.
# Only players with the permission "clickwarp.invwarp.item" can use this function.
EnableInvwarpItem: true
InvwarpItem: clock

#show Invwarp-menu on /warp
InvwarpInsteadWarp: false

#Warp vehicle with you
VehicleWarp: true

# If you wish to use an item that teleports you to a warp
GetWarpItem: true

# The sound who should be played if someone warps
WarpSound: ENTITY_ENDERMEN_TELEPORT 

# If you wish to use an item that teleports you to a player
GetTpSkull: true

# If you wish to use an item that opens the "/invtp" menu, enable it here and define an item.
# Only players with the permission "clickwarp.invtp.item" can use this function.
EnableInvtpItem: true
InvtpItem: book

# The Distance the player should have to the warp
minDistance: 1

Sign:
  # Here you can edit the text that is replaced on a sign, if you write [Warp] in the first line.
  FirstLine: '&7[&6Warp&7]'

Delay:
  Warp:
    # Should a warp delay be activated?
    # Regardless, players with the permission "clickwarp.warp.instant" can warp immediately.
    EnableDelay: false

    # If true, the delay (seconds) can be specified here:
    Delay: 10

    # Shouldn't players move before teleport?
    EnableDontMove: true
    
    Sign:
      # Should there also be a delay when using warp-signs?
      Enable: true

  Teleport:
    # Should a teleport delay be activated?
    # Regardless, players with the permission "clickwarp.teleport.instant" can teleport immediately.
    EnableDelay: false

    # If true, the delay (seconds) can be specified here:
    Delay: 10

    # Shouldn't players move before teleport?
    EnableDontMove: true

# Edit the names of the inventorys here
Inventory:
  Warp: '&2&lWarps'
  Teleport: '&4&lTeleport'

# For this function you need Vault enabled on your server
# Download it at http://dev.bukkit.org/server-mods/vault/
Economy:
  # After setting this to "true", you have to reload/restart your server!
  Enable: false
  
  # Should the price be shown in /invwarp (last line)?
  ShowPrice: true
  
  # Edit here the format of the price:
  PriceFormat: '&7&oPrice: &6&o{price} {currency}'
  
  CurrencySingular: 'Dollar'
  CurrencyPlural: 'Dollars'

# If you want import/export the warps from/to Essentials
# Essentials must be installed for this option
EnableEssentialsWarps: false
# End of the config #